services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secure_root_pass
      MARIADB_DATABASE: appdb
      MARIADB_USER: my_app_user
      MARIADB_PASSWORD: my_secure_app_pass
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql